### ISSUE TITLE
Rename onStartDrag to onDragStart, etc

### ISSUE THREAD

**Issue by charlestbell** [fivecar/react-native-draglist#17]
Hello, me again.

This is more of a discussion topic, but there isn't a discussion option on this repo, so here I am. 

For a future version of the API, may I suggest changing 
onStartDrag => onDragStart
onEndDrag => onDragEnd 

to more closely match other, similar packages and apis.

It seems like a small thing, but it has created an issue for me 3 times now. I typed it wrong, and I was scratching my head wondering why nothing was working. 

Thanks again for an excellent package!

**Comment by fivecar** [comment]
Such great feedback. Done with #18. Launched with https://github.com/fivecar/react-native-draglist/releases/tag/3.5.0.
