### ISSUE TITLE
FlashList

### ISSUE THREAD

**Issue by ahansson89** [fivecar/react-native-draglist#24]
Any plans on adopting FlashList for this library? For long lists, the performance is very noticeable.

**Comment by fivecar** [comment]
I could see making a fork of this repo and supporting it, but it's not likely that we'll adopt it in this current project, because `FlashList` requires installing native binaries (instead of the current design, which intentionally keeps things down to just `react` and `react-native` as requirements).

Let me keep this issue open, since when I have time, I might be able to just fork it myself and do the work.

**Comment by kav** [comment]
Haven't looked at all but allowing a custom FlatList to be provided via prop might be worth considering here. No additional dependency and could support other flat list replacements.

**Comment by fivecar** [comment]
Oh, interesting idea, @kav. Haven't had time recently to look into it, but am happy to take PRs if anyone feels strongly.

**Comment by fivecar** [comment]
Implemented as #62 , based on @kav 's PR. Released as [3.8.0](https://github.com/fivecar/react-native-draglist/releases/tag/3.8.0). @ahansson89 : LMK if FlashList works out well!

**Comment by cyanChill** [comment]
I did end up trying this, which resulted in some errors. After some debugging, I narrowed down a couple of issues:
1. FlashList's implementation of `CellRendererProps` crucially doesn't return `item`, causing `CellRendererComponent` to throw an error from calling `keyExtractor`.
   - We can get an `item` equivalent through the `data` prop on the `children` passed (which is definitely not recommended).
2. The component rendered by `CellRendererComponent` needs to be FlashList's `CellContainer`.
   - Solved by getting its animated variant from `Animated.createAnimatedComponent(CellContainer)`.

See: https://shopify.github.io/flash-list/docs/usage/#cellrenderercomponent

I made a fork with the fixes that makes it work with my limited testing with it so far (haven't touched the example app - just used it with a project I'm working on): https://github.com/MissingCore/react-native-draglist. You can use it as a base if you want to spin up a FlashList implementation as a separate package.

**Comment by fivecar** [comment]
Awesome - thanks for the update, @cyanChill , and for making that available for others!
