### ISSUE TITLE
Autoscroll Speed

### ISSUE THREAD

**Issue by ahansson89** [fivecar/react-native-draglist#25]
I have a long list and the autoscroll speed is way too fast. Would be awesome if there was a way to control the speed.

**Comment by fivecar** [comment]
Ah, interesting. If someone's up for trying it, I believe a change could be made [around this line](https://github.com/fivecar/react-native-draglist/blob/7cbd958fbdb806c82cf7df4f34eec92a306450a7/src/index.tsx#L169) to debounce/throttle the speed at which this is called. Right now, the position is reassessed whenever the drag location is moved; it's quite possible that in some circumstances, this repeats too quickly.

**Comment by fivecar** [comment]
@ahansson89: fix released in [3.7.3](https://github.com/fivecar/react-native-draglist/releases/tag/3.7.0). Thanks for suggesting!
