### ISSUE TITLE
problem with react native web

### ISSUE THREAD

**Issue by pfndesign** [fivecar/react-native-draglist#27]
hi, there was a problem on react-native-web that after the first drag and reorder random items would group together. the issue was that the `onlayout` event is only called once on the web so layouts are not updating. to fix this issue I ended up using a key on DragList to force it to call onLayout again and now it's working without a problem. I thought to share it here for anyone facing the same issue.
also, `onPressOut` wasn't working properly on the web so I had to use the `onMouseUp` event to call `onDragEnd`.
thank you for this awesome package

**Comment by fivecar** [comment]
Thanks for sharing the solutions, @pfndesign. I've not really tried supporting this on web, so I appreciate you letting others know about these fixes. Will leave this issue open so others can see it.

**Comment by ElrohirGT** [comment]
@pfndesign I'm having a problem in web too! But my problem is more about the elements being draged outside of the display area when I try to drag the component up. You can see a demo of the problem in the following video.


https://github.com/fivecar/react-native-draglist/assets/45268815/a8878cb3-9319-4cbc-8c76-e1803266daef

**Comment by fivecar** [comment]
Ok - glad to hear that recent changes have fixed this. Please note that release 3.6.1 fixes a regression caused by #38, so you'll want to take at least 3.6.1.
