### ISSUE TITLE
Horizontal Drag

### ISSUE THREAD

**Issue by Jeffreyoboe1** [fivecar/react-native-draglist#29]
Just making a request that someone add the PR for horizontal DragList.  

Thanks.

**Comment by fivecar** [comment]
@dmytro-lytvyn did this in #33, and I made it generic in #36. Thanks for suggesting! This should now be completed. Simply add `horizontal={true}` to the list (as you would any `FlatList`).

**Comment by fivecar** [comment]
Ok - released in `3.6.0` just now.
