### ISSUE TITLE
First Item wont Drag

### ISSUE THREAD

**Issue by jeokeefe** [fivecar/react-native-draglist#30]
I can't figure this out.... Everything drags as expected EXCEPT the 1st item in the list. This item only "pulls" the list to refresh but does not move the tile itself. All other tiles work as expected. Any thoughts?

**Comment by fivecar** [comment]
Hmm. In the example app in the repro (which pares down an app to the very basics), the first item of both lists drag just fine, even if you supply `onRefresh` and `refreshing` props (i.e. you make it pull-down refreshable.

If you're able to get this to happen in the example app as well, please LMK. This list has been used by many people, and this has never been reported, so I suspect it might have to do with your particular setup....

**Comment by kevmuri** [comment]
I'm seeing this behavior as well with a setup similar to the minimal example. It's just speculation, but the offset when attempting to drag a list item is quite large as well, and I suspect these may be related?
