### ISSUE TITLE
Not working correctly on android devices

### ISSUE THREAD

**Issue by SergiOnGit** [fivecar/react-native-draglist#4]
It works fine on iOS, but in android have dragged item positioning issue. When you start dragging, item is below your finger. If you fix this issue, this will be the best RN draggable plugin.

**Comment by fivecar** [comment]
Ultimately due to a [7-year bug in React Native](https://github.com/facebook/react-native/issues/4753). I've now gone and fixed it by using `LayoutChangeEvent`'s dimensions instead of relying on `measure()`. Verified works on Android.

Launched as v3.0.1. Thanks for reporting the issue!
