### ISSUE TITLE
[Fabric / RN macos 0.76.4] `new NativeEventEmitter()` requires a non-null argument.

### ISSUE THREAD

**Issue by gaeldestrem** [fivecar/react-native-draglist#63]
I'm using your library with react-native-macos. I recently tried try to upgrade from 0.75 to 0.76 and encountered the following error.

<img width="800" alt="Screenshot 2024-12-05 at 15 10 30" src="https://github.com/user-attachments/assets/57b6b41c-58c2-4983-a21f-2349ac3d0348">

Replacing the DragList component with a native FlatList works as expected (without the drag-and-drop feature)

Environment
```
react-native -v: 15.0.1
npm ls react-native-macos: : 0.76.4
node -v: 18.20.5
npm -v: 10.8.2
yarn --version: 1.22.1
xcodebuild -version: Xcode 16.1 (Build version 16B40)
```

**Comment by gaeldestrem** [comment]
The error seems related to this issue : https://github.com/microsoft/react-native-macos/issues/2301

**Comment by fivecar** [comment]
Ah, ok. Thanks for letting me know, @gaeldestrem .
