### ISSUE TITLE
PanResponder yields to Swipeable, even after starting drag

### ISSUE THREAD

**Issue by seanadkinson** [fivecar/react-native-draglist#64]
Hi there, thank you for the library!  I was having issues with `react-native-draggable-flatlist`, so I appreciate the small footprint alternative 🥂 

I'm rendering items in my draglist that are wrapped in `Swipeable`s (from `react-native-gesture-handler/ReanimatedSwipeable`) in order to support "right actions" that allow the user to delete items in the list.  I allow dragging after long press, which is working great, but if the user is reordering and accidentally moves too far left/right with their finger, the Swipeable takes over, and dragging pauses, never working again until the user lifts their finger and starts over.

I personally haven't working too much with the low-level `PanResponder` apis, but I wonder if this is an easy fix.  Something along the lines of "once we have started reordering, we should aggressively not give up being the responder for the current touch".  Is that simple, do you think?

Here is a video of the behavior.  I'm using Simulator, so you can see my mouse movements, but you can't see when I click down or up.  Basically I release the click once I'm stuck in the Swipeable, and click back down in the blank area, which snaps everything back into place.

https://github.com/user-attachments/assets/f3164a46-eb62-4030-bd4b-af285c6f9c2a

Let me know if you need any additional info, or if reproducible sample code would be helpful (I will have time Monday to help).  Thanks again!

**Comment by fivecar** [comment]
@seanadkinson : Thanks for reporting this.

We actually do capture the panResponder as soon as the motion starts, so other react-native components can't steal the gesture halfway through. However, IIUC, Swipeable from react-native-gesture-handler uses native-side things to implement its own gesture handling (which, btw, is why you can't or shouldn't mix its TouchableOpacity components with react-native's own) -- so there might not be much to be done about this (i.e. react-native-gesture-handler is likely the one breaking the pan capture rules).

May be worth posting in react-native-gesture-handler to ask about this. In [looking through their docs](https://docs.swmansion.com/react-native-gesture-handler/docs/components/reanimated_swipeable), it doesn't seem like the component supports a `disabled` property, interestingly; if it did, you might work around this by disabling the Swipeable only when an item is being dragged.

In thinking about it more, you could potentially actually do that -- render the item without a Swipeable wrapping it when it's being dragged. Not awesome, but would work around the issue. Ideal is still to have Swipeable respect pan captures.
