### ISSUE TITLE
Possible to nest lists, for sections?

### ISSUE THREAD

**Issue by sgup** [fivecar/react-native-draglist#65]
I'd like to be able to drag items between sections, and drag whole sections (ideally collapsing the section contents while dragging)

**Comment by fivecar** [comment]
Neat features; agreed that'd be compelling. Perhaps not right for this library, though -- the current library is based on `FlatList`, not `SectionList`; the latter has sections/etc, and has a different API (e.g. complex `data` as opposed to `T[]` for `data`). There wouldn't be a reasonable way to change this library's API to do SectionLists (i.e. without breaking existing users).

Someone could create react-native-draggable-sectionlist, though, and base some logic off this library.
