### ISSUE TITLE
Handling multiple columns

### ISSUE THREAD

**Issue by JB712** [fivecar/react-native-draglist#66]
It seems that dragging is not allowed with multiple columns FlatList.
I thought I had seen somewhere that this behavior is not working on purpose or at least it is known as a fact. But I did not find anything about it so maybe I dreamed it 😅

Anyway my DragList is working perfectly on portrait mode but when I switch to landscape I change **numColumns** property from 1 to 2 (or more depending on screen size).
I work with react-native@0.74.6, react-native-draglist@3.6.2 and it "bugs" on Android and iOS.

I'll drop more info if you tell me it is supposed to work on multiple columns FlatList 🙂

**Comment by JB712** [comment]
Update to  react-native-draglist@3.8.0 and it is still here

**Comment by fivecar** [comment]
Ah, no, this library isn't meant to support multiple column flatlists -- the logic and UI get way more complex. Thanks for clarifying the issue, though!

**Comment by ertucaglar** [comment]
+1

**Comment by fivecar** [comment]
@JB712 : Yah, the complexity of UI of handling dragging items across multiple columns, when each item can be its own different size, is just too complex for anyone to want to handle in a generic way, I bet. Thanks for the update!
