### ISSUE TITLE
Need changelog.md

### ISSUE THREAD

**Issue by SergiOnGit** [fivecar/react-native-draglist#9]
Hello,

This really isn't an issue, but had to reach and ask you. Would be great if you add chanegelog.md or something to let us know what you changed and if anything needs to be changed from our side.

**Comment by fivecar** [comment]
Great suggestion, @SergiOnGit . When I have a chance, I'd like to adopt semantic versioning with something that auto-captures changes since the last release. Will try to get to this prior to the next fix (which I'm actively working on).

Thank you!

**Comment by fivecar** [comment]
Ok - finally also got this to work with automated GitHub releases as well: https://github.com/fivecar/react-native-draglist/releases/tag/3.2.0

[CHANGELOG.md](https://github.com/fivecar/react-native-draglist/blob/main/CHANGELOG.md) also generated all the way back to initial release. Thanks for your suggestion, @SergiOnGit
